spring:
  datasource:
    username: admin
    password: 123456
    url: jdbc:postgresql://localhost:5432/postgres?serverTimezone=UTC+5
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: 'Asia/Almaty'
  jwt:
    secret: secret
  mail:
    host: smtp.gmail.com
    port: 587
    username: yesset.assan@gmail.com
    password: tnvqyiriqnefkzwt
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
server:
  port: 8081
